[package]
name = "witx-bindgen-gen-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
test = false
doctest = false

[dependencies]
witx-bindgen-gen-core = { path = '../gen-core', version = '0.1.0' }
witx-bindgen-gen-rust = { path = '../gen-rust', version = '0.1.0' }
heck = "0.3"
structopt = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
anyhow = "1.0"
test-helpers = { path = '../test-helpers', features = ['witx-bindgen-gen-wasmtime'] }
wasmtime = "0.30.0"
wasmtime-wasi = "0.30.0"
witx-bindgen-wasmtime = { path = '../wasmtime', features = ['tracing', 'async'] }
tokio = { version = "1.0", features = ['rt', 'sync', 'macros', 'rt-multi-thread', 'time'] }

[features]
old-witx-compat = ['witx-bindgen-gen-core/old-witx-compat']
